name: "Build and Push"

inputs:
  VERSION_MAJOR:
    required: true
  DATE_STAMP:
    required: true
  IMAGE_REGISTRY:
    required: true
  REGISTRY_USER:
    required: true
  REGISTRY_PASSWORD:
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare environment
      shell: bash
      run: |
        [[ "${{ env.PLATFORM }}" = */v2 ]] && VARIANT="--variant v2"
        echo "VARIANT=--platform ${{ env.PLATFORM }} ${VARIANT}" >> "$GITHUB_ENV"

        # quay.io/almalinuxorg/almalinux-bootc
        IMAGE_DEST=${{ inputs.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
        echo "IMAGE_DEST=${IMAGE_DEST}" >> "$GITHUB_ENV"

    - name: Check update
      shell: bash
      run: |
        # 'dnf check-update'
        # exit codes:
        #   0 - no updates
        #   100 - updates available
        #   125 - tag/platform not found
        #   127 - command not found
        res=0
        sudo podman run ${{ env.VARIANT }} --quiet --rm ${{ inputs.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.VERSION_MAJOR }} dnf check-update || res=$?
        echo "res=${res}" >> "$GITHUB_ENV"
        echo "Exit code: '$res'"

    - name: Build image
      id: build
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        make image \
          PLATFORM=${{ env.PLATFORM }} \
          IMAGE_NAME=${{ env.IMAGE_NAME }} \
          VERSION_MAJOR=${{ inputs.VERSION_MAJOR }}

        echo "build-time=$(date -Iseconds)" >> $GITHUB_OUTPUT
        echo "image-id=$(cat /tmp/image-id)" >> $GITHUB_OUTPUT

    - name: rechunk image
      id: rechunk
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        make rechunk \
          PLATFORM=${{ env.PLATFORM }} \
          IMAGE_NAME=${{ env.IMAGE_NAME }}

        echo "image-id=sha256:$(sudo podman image inspect ${{ env.IMAGE_NAME }} -f "{{.Id}}")" >> $GITHUB_OUTPUT

    - name: Run Image
      id: run
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      env:
        IMAGE_ID: ${{ steps.rechunk.outputs.image-id }}
      run: |
        sudo podman run ${{ env.VARIANT }} --rm -ti ${{ env.IMAGE_ID }} bootc --version

        INFO=$(sudo podman run ${{ env.VARIANT }} --rm ${{ env.IMAGE_ID }} cat /etc/os-release)
        echo "$INFO"

        echo "id=$(echo "$INFO" | grep "^ID=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT
        echo "version-id=$(echo "$INFO" | grep "^VERSION_ID=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT
        echo "long-version=$(echo "$INFO" | grep "^VERSION_ID=" | cut -d'=' -f2 | tr -d '"').${{ inputs.DATE_STAMP }}.0" >> $GITHUB_OUTPUT
        echo "vendor=$(echo "$INFO" | grep "^VENDOR_NAME=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT

    - name: Image Metadata
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
      id: metadata
      with:
        images: ${{ steps.rechunk.outputs.image-id }}
        labels: |
          redhat.id=${{ steps.run.outputs.id }}
          redhat.version-id=${{ steps.run.outputs.version-id }}
          version=${{ steps.run.outputs.version-id }}
          release=${{ steps.run.outputs.version-id }}
          build-date=${{ steps.build.outputs.build-time }}
          org.opencontainers.image.created=${{ steps.build.outputs.build-time }}
          org.opencontainers.image.vendor=${{ steps.run.outputs.vendor }}
          org.opencontainers.image.version=${{ steps.run.outputs.long-version }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.title=${{ env.IMAGE_NAME }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
        annotations: |
          redhat.id=${{ steps.run.outputs.id }}
          redhat.version-id=${{ steps.run.outputs.version-id }}
          version=${{ steps.run.outputs.version-id }}
          release=${{ steps.run.outputs.version-id }}
          build-date=${{ steps.build.outputs.build-time }}
          org.opencontainers.image.created=${{ steps.build.outputs.build-time }}
          org.opencontainers.image.vendor=${{ steps.run.outputs.vendor }}
          org.opencontainers.image.version=${{ steps.run.outputs.long-version }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.title=${{ env.IMAGE_NAME }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}

    - name: Log in to registry
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: sudo podman login ${{ inputs.IMAGE_REGISTRY }} -u ${{ inputs.REGISTRY_USER }} -p ${{ inputs.REGISTRY_PASSWORD }}

    - name: Push to registry
      id: push
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      env:
        IMAGE_ID: ${{ steps.rechunk.outputs.image-id }}
        VERSION: ${{ steps.run.outputs.version-id }}
      shell: bash
      run: |
        # Tag: VERSION_MAJOR.VERSION_MINOR-DATE_STAMP-ARCH
        sudo podman push --digestfile=/tmp/digestfile ${{ env.IMAGE_ID }} \
          docker://${IMAGE_DEST}:${{ env.VERSION }}-${{ inputs.DATE_STAMP }}-${{ matrix.ARCH }}

        echo "digest=$(cat /tmp/digestfile)" >> $GITHUB_OUTPUT

    - name: Create Job Outputs
      shell: bash
      run: |
        mkdir -p /tmp/outputs/digests
        # using jq, create a json object with the platform as a key, and then a dictionary with the digest, id and version as values
        jq -n --arg platform "${{ matrix.ARCH }}" \
          --arg major "${{ inputs.VERSION_MAJOR }}" \
          --arg digest "${{ steps.push.outputs.digest }}" \
          --arg id "${{ steps.run.outputs.id }}" \
          --arg version "${{ steps.run.outputs.version-id }}" \
          --arg long_version "${{ steps.run.outputs.long-version }}" \
          --arg vendor "${{ steps.run.outputs.vendor }}" \
          --arg image_id "${{ steps.rechunk.outputs.image-id }}" \
          '{($platform): {digest: $digest, id: $id, version: $version, major: $major, long_version: $long_version, vendor: $vendor, image_id: $image_id}}' \
          > /tmp/outputs/digests/${{ env.IMAGE_NAME }}-${{ matrix.VERSION_MAJOR }}-${{ matrix.ARCH }}.json

        cat /tmp/outputs/digests/${{ env.IMAGE_NAME }}-${{ matrix.VERSION_MAJOR }}-${{ matrix.ARCH }}.json

    - name: Upload Output Artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ${{ env.IMAGE_NAME }}-${{ matrix.VERSION_MAJOR }}-${{ matrix.ARCH }}
        retention-days: 1
        if-no-files-found: error
        path: |
          /tmp/outputs/digests/*.json
