FROM almalinux/9-base as repos
FROM quay.io/centos-bootc/bootc-image-builder:latest as builder


COPY --from=repos /etc/dnf/vars /etc/dnf/vars

COPY 9 /src
COPY fedora-bootc /src/fedora-bootc
WORKDIR /src
RUN rm -vf /src/*.repo

COPY --from=repos /etc/yum.repos.d/*.repo /src
COPY --from=repos /etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9 /etc/pki/rpm-gpg

RUN --mount=type=cache,target=/workdir \
    --mount=type=bind,rw=true,src=.,dst=/buildcontext,bind-propagation=shared \
    rpm-ostree compose image \
        --image-config almalinux-bootc-config.json \
        --cachedir=/workdir \
        --format=ociarchive \
        --initialize almalinux-bootc.yaml \
        /buildcontext/out.ociarchive

FROM oci-archive:./out.ociarchive

RUN --mount=type=bind,from=builder,src=.,target=/var/tmp \
    --mount=type=bind,rw=true,src=.,dst=/buildcontext,bind-propagation=shared \
    rm /buildcontext/out.ociarchive
