FROM docker.io/library/almalinux:10-kitten as repos
FROM quay.io/centos-bootc/centos-bootc:stream10 as builder

COPY 10-kitten/almalinux-bootc.yaml /usr/share/doc/bootc-base-imagectl/manifests/

RUN --mount=type=bind,rw,from=repos,src=/,dst=/repos \
    /usr/libexec/bootc-base-imagectl build-rootfs \
        --reinject \
        --manifest=almalinux-bootc \
        /repos \
        /target-rootfs

RUN --mount=type=bind,rw,src=.,dst=/buildcontext,bind-propagation=shared \
    rpm-ostree experimental compose build-chunked-oci \
        --bootc \
        --format-version=1 \
        --rootfs /target-rootfs \
        --output oci-archive:/buildcontext/out.ociarchive

FROM oci-archive:./out.ociarchive

RUN --mount=type=bind,from=builder,src=.,target=/var/tmp \
    --mount=type=bind,rw=true,src=.,dst=/buildcontext,bind-propagation=shared \
    rm /buildcontext/out.ociarchive

# EL compat labels
LABEL containers.bootc="1" \
      ostree.bootable="1" \
      org.opencontainers.image.version="10" \
      redhat.id="almalinux" \
      redhat.version-id="10"
ENV container=oci

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
